[[main]]
  identifier = "ansible"
  name = "Ansible"
  url = "ansible"
  weight = 1

[[main]]
  identifier = "docker"
  name = "Docker"
  url = "docker"
  weight = 2

[[main]]
  identifier = "jenkins"
  name = "Jenkins"
  url = "jenkins"
  weight = 3

[[main]]
  identifier = "misc"
  name = "Misc"
  url = "misc"
  weight = 4

