[[main]]
  identifier = "docs"
  name = "Docs"
  url = "docs"
  weight = 1

[[main]]
  identifier = "CLI"
  name = "CLI"
  url = "cli"
  weight = 2

# [[main]]
#   identifier = "blog"
#   name = "Blog"
#   url = "blog"
#   weight = 3

